export const countryArray = [
    {
        name: "Afghanistan",
        code: "AF",
        flag: "https://flagcdn.com/af.svg",
        nationality: "Afghan",
        currency: "AFN",
        tz: ["Asia/Kabul"],
    },
    {
        name: "Albania",
        code: "AL",
        flag: "https://flagcdn.com/al.svg",
        nationality: "Albanian",
        currency: "ALL",
        tz: ["Europe/Tirane"],
    },
    {
        name: "Algeria",
        code: "DZ",
        flag: "https://flagcdn.com/dz.svg",
        nationality: "Algerian",
        currency: "DZD",
        tz: ["Africa/Algiers"],
    },
    {
        name: "Angola",
        code: "AO",
        flag: "https://flagcdn.com/ao.svg",
        nationality: "Angolan",
        currency: "AOA",
        tz: ["Africa/Lagos", "Africa/Luanda"],
    },
    {
        name: "Argentina",
        code: "AR",
        flag: "https://flagcdn.com/ar.svg",
        nationality: "Argentine",
        currency: "ARS",
        tz: [
            "America/Argentina/Buenos_Aires",
            "America/Argentina/Catamarca",
            "America/Argentina/Cordoba",
            "America/Argentina/Jujuy",
            "America/Argentina/La_Rioja",
            "America/Argentina/Mendoza",
            "America/Argentina/Rio_Gallegos",
            "America/Argentina/Salta",
            "America/Argentina/San_Juan",
            "America/Argentina/San_Luis",
            "America/Argentina/Tucuman",
            "America/Argentina/Ushuaia",
        ],
    },
    {
        name: "Armenia",
        code: "AM",
        flag: "https://flagcdn.com/am.svg",
        nationality: "Armenian",
        currency: "AMD",
        tz: ["Asia/Yerevan"],
    },
    {
        name: "Australia",
        code: "AU",
        flag: "https://flagcdn.com/au.svg",
        nationality: "Australian",
        currency: "AUD",
        tz: [
            "Antarctica/Macquarie",
            "Australia/Adelaide",
            "Australia/Brisbane",
            "Australia/Broken_Hill",
            "Australia/Darwin",
            "Australia/Eucla",
            "Australia/Hobart",
            "Australia/Lindeman",
            "Australia/Lord_Howe",
            "Australia/Melbourne",
            "Australia/Perth",
            "Australia/Sydney",
        ],
    },
    {
        name: "Azerbaijan",
        code: "AZ",
        flag: "https://flagcdn.com/az.svg",
        nationality: "Azerbaijani",
        currency: "AZN",
        tz: ["Asia/Baku"],
    },
    {
        name: "Bahamas",
        code: "BS",
        flag: "https://flagcdn.com/bs.svg",
        nationality: "Bahamian",
        currency: "BSD",
        tz: ["America/Nassau", "America/Toronto"],
    },
    {
        name: "Bahrain",
        code: "BH",
        flag: "https://flagcdn.com/bh.svg",
        nationality: "Bahraini",
        currency: "BHD",
        tz: ["Asia/Bahrain", "Asia/Qatar"],
    },
    {
        name: "Bangladesh",
        code: "BD",
        flag: "https://flagcdn.com/bd.svg",
        nationality: "Bangladeshi",
        currency: "BDT",
        tz: ["Asia/Dhaka"],
    },
    {
        name: "Barbados",
        code: "BB",
        flag: "https://flagcdn.com/bb.svg",
        nationality: "Barbadian",
        currency: "BBD",
        tz: ["America/Barbados"],
    },
    {
        name: "Belarus",
        code: "BY",
        flag: "https://flagcdn.com/by.svg",
        nationality: "Belarusian",
        currency: "BYN",
        tz: ["Europe/Minsk"],
    },
    {
        name: "Belize",
        code: "BZ",
        flag: "https://flagcdn.com/bz.svg",
        nationality: "Belizean",
        currency: "BZD",
        tz: ["America/Belize"],
    },
    {
        name: "Bhutan",
        code: "BT",
        flag: "https://flagcdn.com/bt.svg",
        nationality: "Bhutanese",
        currency: "BTN",
        tz: ["Asia/Thimphu"],
    },
    {
        name: "Bolivia",
        code: "BO",
        flag: "https://flagcdn.com/bo.svg",
        nationality: "Bolivian",
        currency: "BOB",
        tz: ["America/La_Paz"],
    },
    {
        name: "Bosnia and Herzegovina",
        code: "BA",
        flag: "https://flagcdn.com/ba.svg",
        nationality: "Bosnian",
        currency: "BAM",
        tz: ["Europe/Belgrade", "Europe/Sarajevo"],
    },
    {
        name: "Botswana",
        code: "BW",
        flag: "https://flagcdn.com/bw.svg",
        nationality: "Botswanan",
        currency: "BWP",
        tz: ["Africa/Gaborone", "Africa/Maputo"],
    },
    {
        name: "Brazil",
        code: "BR",
        flag: "https://flagcdn.com/br.svg",
        nationality: "Brazilian",
        currency: "BRL",
        tz: [
            "America/Araguaina",
            "America/Bahia",
            "America/Belem",
            "America/Boa_Vista",
            "America/Campo_Grande",
            "America/Cuiaba",
            "America/Eirunepe",
            "America/Fortaleza",
            "America/Maceio",
            "America/Manaus",
            "America/Noronha",
            "America/Porto_Velho",
            "America/Recife",
            "America/Rio_Branco",
            "America/Santarem",
            "America/Sao_Paulo",
        ],
    },
    {
        name: "Brunei",
        code: "BN",
        flag: "https://flagcdn.com/bn.svg",
        nationality: "Bruneian",
        currency: "BND",
        tz: ["Asia/Brunei", "Asia/Kuching"],
    },
    {
        name: "Bulgaria",
        code: "BG",
        flag: "https://flagcdn.com/bg.svg",
        nationality: "Bulgarian",
        currency: "BGN",
        tz: ["Europe/Sofia"],
    },
    {
        name: "Burundi",
        code: "BI",
        flag: "https://flagcdn.com/bi.svg",
        nationality: "Burundian",
        currency: "BIF",
        tz: ["Africa/Bujumbura", "Africa/Maputo"],
    },
    {
        name: "Cambodia",
        code: "KH",
        flag: "https://flagcdn.com/kh.svg",
        nationality: "Cambodian",
        currency: "KHR",
        tz: ["Asia/Bangkok", "Asia/Phnom_Penh"],
    },
    {
        name: "Canada",
        code: "CA",
        flag: "https://flagcdn.com/ca.svg",
        nationality: "Canadian",
        currency: "CAD",
        tz: [
            "America/Atikokan",
            "America/Blanc-Sablon",
            "America/Cambridge_Bay",
            "America/Creston",
            "America/Dawson",
            "America/Dawson_Creek",
            "America/Edmonton",
            "America/Fort_Nelson",
            "America/Glace_Bay",
            "America/Goose_Bay",
            "America/Halifax",
            "America/Inuvik",
            "America/Iqaluit",
            "America/Moncton",
            "America/Panama",
            "America/Phoenix",
            "America/Puerto_Rico",
            "America/Rankin_Inlet",
            "America/Regina",
            "America/Resolute",
            "America/St_Johns",
            "America/Swift_Current",
            "America/Toronto",
            "America/Vancouver",
            "America/Whitehorse",
            "America/Winnipeg",
        ],
    },
    {
        name: "Chile",
        code: "CL",
        flag: "https://flagcdn.com/cl.svg",
        nationality: "Chilean",
        currency: "CLP",
        tz: ["America/Punta_Arenas", "America/Santiago", "Pacific/Easter"],
    },
    {
        name: "China",
        code: "CN",
        flag: "https://flagcdn.com/cn.svg",
        nationality: "Chinese",
        currency: "CNY",
        tz: ["Asia/Shanghai", "Asia/Urumqi"],
    },
    {
        name: "Colombia",
        code: "CO",
        flag: "https://flagcdn.com/co.svg",
        nationality: "Colombian",
        currency: "COP",
        tz: ["America/Bogota"],
    },
    {
        name: "Comoros",
        code: "KM",
        flag: "https://flagcdn.com/km.svg",
        nationality: "Comorian",
        currency: "KMF",
        tz: ["Africa/Nairobi", "Indian/Comoro"],
    },
    {
        name: "Costa Rica",
        code: "CR",
        flag: "https://flagcdn.com/cr.svg",
        nationality: "Costa Rican",
        currency: "CRC",
        tz: ["America/Costa_Rica"],
    },
    {
        name: "Croatia",
        code: "HR",
        flag: "https://flagcdn.com/hr.svg",
        nationality: "Croatian",
        currency: "HRK",
        tz: ["Europe/Belgrade", "Europe/Zagreb"],
    },
    {
        name: "Cuba",
        code: "CU",
        flag: "https://flagcdn.com/cu.svg",
        nationality: "Cuban",
        currency: "CUC",
        tz: ["America/Havana"],
    },
    {
        name: "Denmark",
        code: "DK",
        flag: "https://flagcdn.com/dk.svg",
        nationality: "Danish",
        currency: "DKK",
        tz: ["Europe/Berlin", "Europe/Copenhagen"],
    },
    {
        name: "Djibouti",
        code: "DJ",
        flag: "https://flagcdn.com/dj.svg",
        nationality: "Djibouti",
        currency: "DJF",
        tz: ["Africa/Djibouti", "Africa/Nairobi"],
    },
    {
        name: "Dominican Republic",
        code: "DO",
        flag: "https://flagcdn.com/do.svg",
        nationality: "Dominican",
        currency: "DOP",
        tz: ["America/Santo_Domingo"],
    },
    {
        name: "Egypt",
        code: "EG",
        flag: "https://flagcdn.com/eg.svg",
        nationality: "Egyptian",
        currency: "EGP",
        tz: ["Africa/Cairo"],
    },
    {
        name: "El Salvador",
        code: "SV",
        flag: "https://flagcdn.com/sv.svg",
        nationality: "Salvadoran",
        currency: "SVC",
        tz: ["America/El_Salvador"],
    },
    {
        name: "Eritrea",
        code: "ER",
        flag: "https://flagcdn.com/er.svg",
        nationality: "Eritrean",
        currency: "ERN",
        tz: ["Africa/Asmara", "Africa/Nairobi"],
    },
    {
        name: "Ethiopia",
        code: "ET",
        flag: "https://flagcdn.com/et.svg",
        nationality: "Ethiopian",
        currency: "ETB",
        tz: ["Africa/Addis_Ababa", "Africa/Nairobi"],
    },
    {
        name: "Fiji",
        code: "FJ",
        flag: "https://flagcdn.com/fj.svg",
        nationality: "Fijian",
        currency: "FJD",
        tz: ["Pacific/Fiji"],
    },
    {
        name: "Gambia",
        code: "GM",
        flag: "https://flagcdn.com/gm.svg",
        nationality: "Gambian",
        currency: "GMD",
        tz: ["Africa/Abidjan", "Africa/Banjul"],
    },
    {
        name: "Georgia",
        code: "GE",
        flag: "https://flagcdn.com/ge.svg",
        nationality: "Georgian",
        currency: "GEL",
        tz: ["Asia/Tbilisi"],
    },
    {
        name: "Ghana",
        code: "GH",
        flag: "https://flagcdn.com/gh.svg",
        nationality: "Ghanaian",
        currency: "GHS",
        tz: ["Africa/Abidjan", "Africa/Accra"],
    },
    {
        name: "Guatemala",
        code: "GT",
        flag: "https://flagcdn.com/gt.svg",
        nationality: "Guatemalan",
        currency: "GTQ",
        tz: ["America/Guatemala"],
    },
    {
        name: "Guinea",
        code: "GN",
        flag: "https://flagcdn.com/gn.svg",
        nationality: "Guinean",
        currency: "GNF",
        tz: ["Africa/Abidjan", "Africa/Conakry"],
    },
    {
        name: "Guyana",
        code: "GY",
        flag: "https://flagcdn.com/gy.svg",
        nationality: "Guyanese",
        currency: "GYD",
        tz: ["America/Guyana"],
    },
    {
        name: "Haiti",
        code: "HT",
        flag: "https://flagcdn.com/ht.svg",
        nationality: "Haitian",
        currency: "HTG",
        tz: ["America/Port-au-Prince"],
    },
    {
        name: "Honduras",
        code: "HN",
        flag: "https://flagcdn.com/hn.svg",
        nationality: "Honduran",
        currency: "HNL",
        tz: ["America/Tegucigalpa"],
    },
    {
        name: "Hungary",
        code: "HU",
        flag: "https://flagcdn.com/hu.svg",
        nationality: "Hungarian",
        currency: "HUF",
        tz: ["Europe/Budapest"],
    },
    {
        name: "Iceland",
        code: "IS",
        flag: "https://flagcdn.com/is.svg",
        nationality: "Icelander",
        currency: "ISK",
        tz: ["Africa/Abidjan", "Atlantic/Reykjavik"],
    },
    {
        name: "India",
        code: "IN",
        flag: "https://flagcdn.com/in.svg",
        nationality: "Indian",
        currency: "INR",
        tz: ["Asia/Kolkata"],
    },
    {
        name: "Indonesia",
        code: "ID",
        flag: "https://flagcdn.com/id.svg",
        nationality: "Indonesian",
        currency: "IDR",
        tz: [
            "Asia/Jakarta",
            "Asia/Jayapura",
            "Asia/Makassar",
            "Asia/Pontianak",
        ],
    },
    {
        name: "Iran",
        code: "IR",
        flag: "https://flagcdn.com/ir.svg",
        nationality: "Iranian",
        currency: "IRR",
        tz: ["Asia/Tehran"],
    },
    {
        name: "Iraq",
        code: "IQ",
        flag: "https://flagcdn.com/iq.svg",
        nationality: "Iraqi",
        currency: "IQD",
        tz: ["Asia/Baghdad"],
    },
    {
        name: "Israel",
        code: "IL",
        flag: "https://flagcdn.com/il.svg",
        nationality: "Israeli",
        currency: "ILS",
        tz: ["Asia/Jerusalem"],
    },
    {
        name: "Jamaica",
        code: "JM",
        flag: "https://flagcdn.com/jm.svg",
        nationality: "Jamaican",
        currency: "JMD",
        tz: ["America/Jamaica"],
    },
    {
        name: "Japan",
        code: "JP",
        flag: "https://flagcdn.com/jp.svg",
        nationality: "Japanese",
        currency: "JPY",
        tz: ["Asia/Tokyo"],
    },
    {
        name: "Jordan",
        code: "JO",
        flag: "https://flagcdn.com/jo.svg",
        nationality: "Jordanian",
        currency: "JOD",
        tz: ["Asia/Amman"],
    },
    {
        name: "Kazakhstan",
        code: "KZ",
        flag: "https://flagcdn.com/kz.svg",
        nationality: "Kazakhstani",
        currency: "KZT",
        tz: [
            "Asia/Almaty",
            "Asia/Aqtau",
            "Asia/Aqtobe",
            "Asia/Atyrau",
            "Asia/Oral",
            "Asia/Qostanay",
            "Asia/Qyzylorda",
        ],
    },
    {
        name: "Kenya",
        code: "KE",
        flag: "https://flagcdn.com/ke.svg",
        nationality: "Kenyan",
        currency: "KES",
        tz: ["Africa/Nairobi"],
    },
    {
        name: "Kuwait",
        code: "KW",
        flag: "https://flagcdn.com/kw.svg",
        nationality: "Kuwaiti",
        currency: "KWD",
        tz: ["Asia/Kuwait", "Asia/Riyadh"],
    },
    {
        name: "Kyrgyzstan",
        code: "KG",
        flag: "https://flagcdn.com/kg.svg",
        nationality: "Kyrgyzstani",
        currency: "KGS",
        tz: ["Asia/Bishkek"],
    },
    {
        name: "Laos",
        code: "LA",
        flag: "https://flagcdn.com/la.svg",
        nationality: "Laotian",
        currency: "LAK",
        tz: ["Asia/Bangkok", "Asia/Vientiane"],
    },
    {
        name: "Lebanon",
        code: "LB",
        flag: "https://flagcdn.com/lb.svg",
        nationality: "Lebanese",
        currency: "LBP",
        tz: ["Asia/Beirut"],
    },
    {
        name: "Lesotho",
        code: "LS",
        flag: "https://flagcdn.com/ls.svg",
        nationality: "Mosotho",
        currency: "LSL",
        tz: ["Africa/Johannesburg", "Africa/Maseru"],
    },
    {
        name: "Liberia",
        code: "LR",
        flag: "https://flagcdn.com/lr.svg",
        nationality: "Liberian",
        currency: "LRD",
        tz: ["Africa/Monrovia"],
    },
    {
        name: "Libya",
        code: "LY",
        flag: "https://flagcdn.com/ly.svg",
        nationality: "Libyan",
        currency: "LYD",
        tz: ["Africa/Tripoli"],
    },
    {
        name: "Madagascar",
        code: "MG",
        flag: "https://flagcdn.com/mg.svg",
        nationality: "Malagasy",
        currency: "MGA",
        tz: ["Africa/Nairobi", "Indian/Antananarivo"],
    },
    {
        name: "Malawi",
        code: "MW",
        flag: "https://flagcdn.com/mw.svg",
        nationality: "Malawian",
        currency: "MWK",
        tz: ["Africa/Blantyre", "Africa/Maputo"],
    },
    {
        name: "Malaysia",
        code: "MY",
        flag: "https://flagcdn.com/my.svg",
        nationality: "Malaysian",
        currency: "MYR",
        tz: ["Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Singapore"],
    },
    {
        name: "Maldives",
        code: "MV",
        flag: "https://flagcdn.com/mv.svg",
        nationality: "Maldivian",
        currency: "MVR",
        tz: ["Indian/Maldives"],
    },
    {
        name: "Mauritania",
        code: "MR",
        flag: "https://flagcdn.com/mr.svg",
        nationality: "Mauritanian",
        currency: "MRU",
        tz: ["Africa/Abidjan", "Africa/Nouakchott"],
    },
    {
        name: "Mauritius",
        code: "MU",
        flag: "https://flagcdn.com/mu.svg",
        nationality: "Mauritian",
        currency: "MUR",
        tz: ["Indian/Mauritius"],
    },
    {
        name: "Mexico",
        code: "MX",
        flag: "https://flagcdn.com/mx.svg",
        nationality: "Mexican",
        currency: "MXN",
        tz: [
            "America/Bahia_Banderas",
            "America/Cancun",
            "America/Chihuahua",
            "America/Ciudad_Juarez",
            "America/Hermosillo",
            "America/Matamoros",
            "America/Mazatlan",
            "America/Merida",
            "America/Mexico_City",
            "America/Monterrey",
            "America/Ojinaga",
            "America/Tijuana",
        ],
    },
    {
        name: "Moldova",
        code: "MD",
        flag: "https://flagcdn.com/md.svg",
        nationality: "Moldovan",
        currency: "MDL",
        tz: ["Europe/Chisinau"],
    },
    {
        name: "Mongolia",
        code: "MN",
        flag: "https://flagcdn.com/mn.svg",
        nationality: "Mongolian",
        currency: "MNT",
        tz: ["Asia/Choibalsan", "Asia/Hovd", "Asia/Ulaanbaatar"],
    },
    {
        name: "Morocco",
        code: "MA",
        flag: "https://flagcdn.com/ma.svg",
        nationality: "Moroccan",
        currency: "MAD",
        tz: ["Africa/Casablanca"],
    },
    {
        name: "Mozambique",
        code: "MZ",
        flag: "https://flagcdn.com/mz.svg",
        nationality: "Mozambican",
        currency: "MZN",
        tz: ["Africa/Maputo"],
    },
    {
        name: "Namibia",
        code: "NA",
        flag: "https://flagcdn.com/na.svg",
        nationality: "Namibian",
        currency: "NAD",
        tz: ["Africa/Windhoek"],
    },
    {
        name: "Nepal",
        code: "NP",
        flag: "https://flagcdn.com/np.svg",
        nationality: "Nepali",
        currency: "NPR",
        tz: ["Asia/Kathmandu"],
    },
    {
        name: "New Zealand",
        code: "NZ",
        flag: "https://flagcdn.com/nz.svg",
        nationality: "New Zealander",
        currency: "NZD",
        tz: ["Pacific/Auckland", "Pacific/Chatham"],
    },
    {
        name: "Nicaragua",
        code: "NI",
        flag: "https://flagcdn.com/ni.svg",
        nationality: "Nicaraguan",
        currency: "NIO",
        tz: ["America/Managua"],
    },
    {
        name: "Nigeria",
        code: "NG",
        flag: "https://flagcdn.com/ng.svg",
        nationality: "Nigerian",
        currency: "NGN",
        tz: ["Africa/Lagos"],
    },
    {
        name: "North Macedonia",
        code: "MK",
        flag: "https://flagcdn.com/mk.svg",
        nationality: "Macedonian",
        currency: "MKD",
        tz: ["Europe/Belgrade", "Europe/Skopje"],
    },
    {
        name: "Norway",
        code: "NO",
        flag: "https://flagcdn.com/no.svg",
        nationality: "Norwegian",
        currency: "NOK",
        tz: ["Europe/Berlin", "Europe/Oslo"],
    },
    {
        name: "Oman",
        code: "OM",
        flag: "https://flagcdn.com/om.svg",
        nationality: "Omani",
        currency: "OMR",
        tz: ["Asia/Dubai", "Asia/Muscat"],
    },
    {
        name: "Pakistan",
        code: "PK",
        flag: "https://flagcdn.com/pk.svg",
        nationality: "Pakistani",
        currency: "PKR",
        tz: ["Asia/Karachi"],
    },
    {
        name: "Panama",
        code: "PA",
        flag: "https://flagcdn.com/pa.svg",
        nationality: "Panamanian",
        currency: "PAB",
        tz: ["America/Panama"],
    },
    {
        name: "Papua New Guinea",
        code: "PG",
        flag: "https://flagcdn.com/pg.svg",
        nationality: "Papua New Guinean",
        currency: "PGK",
        tz: ["Pacific/Bougainville", "Pacific/Port_Moresby"],
    },
    {
        name: "Paraguay",
        code: "PY",
        flag: "https://flagcdn.com/py.svg",
        nationality: "Paraguayan",
        currency: "PYG",
        tz: ["America/Asuncion"],
    },
    {
        name: "Peru",
        code: "PE",
        flag: "https://flagcdn.com/pe.svg",
        nationality: "Peruvian",
        currency: "PEN",
        tz: ["America/Lima"],
    },
    {
        name: "Philippines",
        code: "PH",
        flag: "https://flagcdn.com/ph.svg",
        nationality: "Filipino",
        currency: "PHP",
        tz: ["Asia/Manila"],
    },
    {
        name: "Poland",
        code: "PL",
        flag: "https://flagcdn.com/pl.svg",
        nationality: "Polish",
        currency: "PLN",
        tz: ["Europe/Warsaw"],
    },
    {
        name: "Qatar",
        code: "QA",
        flag: "https://flagcdn.com/qa.svg",
        nationality: "Qatari",
        currency: "QAR",
        tz: ["Asia/Qatar"],
    },
    {
        name: "Romania",
        code: "RO",
        flag: "https://flagcdn.com/ro.svg",
        nationality: "Romanian",
        currency: "RON",
        tz: ["Europe/Bucharest"],
    },
    {
        name: "Russia",
        code: "RU",
        flag: "https://flagcdn.com/ru.svg",
        nationality: "Russian",
        currency: "RUB",
        tz: [
            "Asia/Anadyr",
            "Asia/Barnaul",
            "Asia/Chita",
            "Asia/Irkutsk",
            "Asia/Kamchatka",
            "Asia/Khandyga",
            "Asia/Krasnoyarsk",
            "Asia/Magadan",
            "Asia/Novokuznetsk",
            "Asia/Novosibirsk",
            "Asia/Omsk",
            "Asia/Sakhalin",
            "Asia/Srednekolymsk",
            "Asia/Tomsk",
            "Asia/Ust-Nera",
            "Asia/Vladivostok",
            "Asia/Yakutsk",
            "Asia/Yekaterinburg",
            "Europe/Astrakhan",
            "Europe/Kaliningrad",
            "Europe/Kirov",
            "Europe/Moscow",
            "Europe/Samara",
            "Europe/Saratov",
            "Europe/Simferopol",
            "Europe/Ulyanovsk",
            "Europe/Volgograd",
        ],
    },
    {
        name: "Rwanda",
        code: "RW",
        flag: "https://flagcdn.com/rw.svg",
        nationality: "Rwandan",
        currency: "RWF",
        tz: ["Africa/Kigali", "Africa/Maputo"],
    },
    {
        name: "Samoa",
        code: "WS",
        flag: "https://flagcdn.com/ws.svg",
        nationality: "Samoan",
        currency: "WST",
        tz: ["Pacific/Apia"],
    },
    {
        name: "Saudi Arabia",
        code: "SA",
        flag: "https://flagcdn.com/sa.svg",
        nationality: "Saudi Arabian",
        currency: "SAR",
        tz: ["Asia/Riyadh"],
    },
    {
        name: "Serbia",
        code: "RS",
        flag: "https://flagcdn.com/rs.svg",
        nationality: "Serbian",
        currency: "RSD",
        tz: ["Europe/Belgrade"],
    },
    {
        name: "Seychelles",
        code: "SC",
        flag: "https://flagcdn.com/sc.svg",
        nationality: "Seychellois",
        currency: "SCR",
        tz: ["Asia/Dubai", "Indian/Mahe"],
    },
    {
        name: "Sierra Leone",
        code: "SL",
        flag: "https://flagcdn.com/sl.svg",
        nationality: "Sierra Leonean",
        currency: "SLL",
        tz: ["Africa/Abidjan", "Africa/Freetown"],
    },
    {
        name: "Singapore",
        code: "SG",
        flag: "https://flagcdn.com/sg.svg",
        nationality: "Singaporean",
        currency: "SGD",
        tz: ["Asia/Singapore"],
    },
    {
        name: "Solomon Islands",
        code: "SB",
        flag: "https://flagcdn.com/sb.svg",
        nationality: "Solomon Islander",
        currency: "SBD",
        tz: ["Pacific/Guadalcanal"],
    },
    {
        name: "Somalia",
        code: "SO",
        flag: "https://flagcdn.com/so.svg",
        nationality: "Somali",
        currency: "SOS",
        tz: ["Africa/Mogadishu", "Africa/Nairobi"],
    },
    {
        name: "South Africa",
        code: "ZA",
        flag: "https://flagcdn.com/za.svg",
        nationality: "South African",
        currency: "ZAR",
        tz: ["Africa/Johannesburg"],
    },
    {
        name: "South Korea",
        code: "KR",
        flag: "https://flagcdn.com/kr.svg",
        nationality: "South Korean",
        currency: "KRW",
        tz: ["Asia/Seoul"],
    },
    {
        name: "Sri Lanka",
        code: "LK",
        flag: "https://flagcdn.com/lk.svg",
        nationality: "Sri Lankan",
        currency: "LKR",
        tz: ["Asia/Colombo"],
    },
    {
        name: "Sudan",
        code: "SD",
        flag: "https://flagcdn.com/sd.svg",
        nationality: "Sudanese",
        currency: "SDG",
        tz: ["Africa/Khartoum"],
    },
    {
        name: "Suriname",
        code: "SR",
        flag: "https://flagcdn.com/sr.svg",
        nationality: "Surinamese",
        currency: "SRD",
        tz: ["America/Paramaribo"],
    },
    {
        name: "Sweden",
        code: "SE",
        flag: "https://flagcdn.com/se.svg",
        nationality: "Swedish",
        currency: "SEK",
        tz: ["Europe/Berlin", "Europe/Stockholm"],
    },
    {
        name: "Switzerland",
        code: "CH",
        flag: "https://flagcdn.com/ch.svg",
        nationality: "Swiss",
        currency: "CHF",
        tz: ["Europe/Zurich"],
    },
    {
        name: "Syria",
        code: "SY",
        flag: "https://flagcdn.com/sy.svg",
        nationality: "Syrian",
        currency: "SYP",
        tz: ["Asia/Damascus"],
    },
    {
        name: "Tajikistan",
        code: "TJ",
        flag: "https://flagcdn.com/tj.svg",
        nationality: "Tajik",
        currency: "TJS",
        tz: ["Asia/Dushanbe"],
    },
    {
        name: "Tanzania",
        code: "TZ",
        flag: "https://flagcdn.com/tz.svg",
        nationality: "Tanzanian",
        currency: "TZS",
        tz: ["Africa/Dar_es_Salaam", "Africa/Nairobi"],
    },
    {
        name: "Thailand",
        code: "TH",
        flag: "https://flagcdn.com/th.svg",
        nationality: "Thai",
        currency: "THB",
        tz: ["Asia/Bangkok"],
    },
    {
        name: "Tonga",
        code: "TO",
        flag: "https://flagcdn.com/to.svg",
        nationality: "Tongan",
        currency: "TOP",
        tz: ["Pacific/Tongatapu"],
    },
    {
        name: "Trinidad and Tobago",
        code: "TT",
        flag: "https://flagcdn.com/tt.svg",
        nationality: "Trinidadian and Tobagonian",
        currency: "TTD",
        tz: ["America/Port_of_Spain", "America/Puerto_Rico"],
    },
    {
        name: "Tunisia",
        code: "TN",
        flag: "https://flagcdn.com/tn.svg",
        nationality: "Tunisian",
        currency: "TND",
        tz: ["Africa/Tunis"],
    },
    {
        name: "Turkey",
        code: "TR",
        flag: "https://flagcdn.com/tr.svg",
        nationality: "Turkish",
        currency: "TRY",
        tz: ["Europe/Istanbul"],
    },
    {
        name: "Turkmenistan",
        code: "TM",
        flag: "https://flagcdn.com/tm.svg",
        nationality: "Turkmen",
        currency: "TMT",
        tz: ["Asia/Ashgabat"],
    },
    {
        name: "Tuvalu",
        code: "TV",
        flag: "https://flagcdn.com/tv.svg",
        nationality: "Tuvaluan",
        currency: "TVD",
        tz: ["Pacific/Funafuti", "Pacific/Tarawa"],
    },
    {
        name: "Uganda",
        code: "UG",
        flag: "https://flagcdn.com/ug.svg",
        nationality: "Ugandan",
        currency: "UGX",
        tz: ["Africa/Kampala", "Africa/Nairobi"],
    },
    {
        name: "Ukraine",
        code: "UA",
        flag: "https://flagcdn.com/ua.svg",
        nationality: "Ukrainian",
        currency: "UAH",
        tz: ["Europe/Kyiv", "Europe/Simferopol"],
    },
    {
        name: "United Arab Emirates",
        code: "AE",
        flag: "https://flagcdn.com/ae.svg",
        nationality: "Emirati",
        currency: "AED",
        tz: ["Asia/Dubai"],
    },
    {
        name: "United Kingdom",
        code: "GB",
        flag: "https://flagcdn.com/gb.svg",
        nationality: "British",
        currency: "GBP",
        tz: ["Europe/London"],
    },
    {
        name: "United States",
        code: "US",
        flag: "https://flagcdn.com/us.svg",
        nationality: "American",
        currency: "USD",
        tz: [
            "America/Adak",
            "America/Anchorage",
            "America/Boise",
            "America/Chicago",
            "America/Denver",
            "America/Detroit",
            "America/Indiana/Indianapolis",
            "America/Indiana/Knox",
            "America/Indiana/Marengo",
            "America/Indiana/Petersburg",
            "America/Indiana/Tell_City",
            "America/Indiana/Vevay",
            "America/Indiana/Vincennes",
            "America/Indiana/Winamac",
            "America/Juneau",
            "America/Kentucky/Louisville",
            "America/Kentucky/Monticello",
            "America/Los_Angeles",
            "America/Menominee",
            "America/Metlakatla",
            "America/New_York",
            "America/Nome",
            "America/North_Dakota/Beulah",
            "America/North_Dakota/Center",
            "America/North_Dakota/New_Salem",
            "America/Phoenix",
            "America/Sitka",
            "America/Yakutat",
            "Pacific/Honolulu",
        ],
    },
    {
        name: "Uruguay",
        code: "UY",
        flag: "https://flagcdn.com/uy.svg",
        nationality: "Uruguayan",
        currency: "UYU",
        tz: ["America/Montevideo"],
    },
    {
        name: "Uzbekistan",
        code: "UZ",
        flag: "https://flagcdn.com/uz.svg",
        nationality: "Uzbek",
        currency: "UZS",
        tz: ["Asia/Samarkand", "Asia/Tashkent"],
    },
    {
        name: "Vanuatu",
        code: "VU",
        flag: "https://flagcdn.com/vu.svg",
        nationality: "Vanuatuan",
        currency: "VUV",
        tz: ["Pacific/Efate"],
    },
    {
        name: "Venezuela",
        code: "VE",
        flag: "https://flagcdn.com/ve.svg",
        nationality: "Venezuelan",
        currency: "VEF",
        tz: ["America/Caracas"],
    },
    {
        name: "Vietnam",
        code: "VN",
        flag: "https://flagcdn.com/vn.svg",
        nationality: "Vietnamese",
        currency: "VND",
        tz: ["Asia/Bangkok", "Asia/Ho_Chi_Minh"],
    },
    {
        name: "Yemen",
        code: "YE",
        flag: "https://flagcdn.com/ye.svg",
        nationality: "Yemeni",
        currency: "YER",
        tz: ["Asia/Aden", "Asia/Riyadh"],
    },
    {
        name: "Zambia",
        code: "ZM",
        flag: "https://flagcdn.com/zm.svg",
        nationality: "Zambian",
        currency: "ZMW",
        tz: ["Africa/Lusaka", "Africa/Maputo"],
    },
    {
        name: "Zimbabwe",
        code: "ZW",
        flag: "https://flagcdn.com/zw.svg",
        nationality: "Zimbabwean",
        currency: "ZWD",
        tz: ["Africa/Harare", "Africa/Maputo"],
    },
] as const;
