const countryArray = [
    { country: "Afghanistan", nationality: "Afghan" },
    { country: "Albania", nationality: "Albanian" },
    { country: "Algeria", nationality: "Algerian" },
    { country: "Andorra", nationality: "Andorran" },
    { country: "Angola", nationality: "Angolan" },
    { country: "Antigua and Barbuda", nationality: "Antiguan" },
    { country: "Argentina", nationality: "Argentine" },
    { country: "Armenia", nationality: "Armenian" },
    { country: "Australia", nationality: "Australian" },
    { country: "Austria", nationality: "Austrian" },
    { country: "Azerbaijan", nationality: "Azerbaijani" },
    { country: "Bahamas", nationality: "Bahamian" },
    { country: "Bahrain", nationality: "Bahraini" },
    { country: "Bangladesh", nationality: "Bangladeshi" },
    { country: "Barbados", nationality: "Barbadian" },
    { country: "Belarus", nationality: "Belarusian" },
    { country: "Belgium", nationality: "Belgian" },
    { country: "Belize", nationality: "Belizean" },
    { country: "Benin", nationality: "Beninese" },
    { country: "Bhutan", nationality: "Bhutanese" },
    { country: "Bolivia", nationality: "Bolivian" },
    { country: "Bosnia and Herzegovina", nationality: "Bosnian" },
    { country: "Botswana", nationality: "Botswanan" },
    { country: "Brazil", nationality: "Brazilian" },
    { country: "Brunei", nationality: "Bruneian" },
    { country: "Bulgaria", nationality: "Bulgarian" },
    { country: "Burkina Faso", nationality: "Burkinabe" },
    { country: "Burundi", nationality: "Burundian" },
    { country: "Cabo Verde", nationality: "Cape Verdean" },
    { country: "Cambodia", nationality: "Cambodian" },
    { country: "Cameroon", nationality: "Cameroonian" },
    { country: "Canada", nationality: "Canadian" },
    { country: "Central African Republic", nationality: "Central African" },
    { country: "Chad", nationality: "Chadian" },
    { country: "Chile", nationality: "Chilean" },
    { country: "China", nationality: "Chinese" },
    { country: "Colombia", nationality: "Colombian" },
    { country: "Comoros", nationality: "Comorian" },
    { country: "Congo (Congo-Brazzaville)", nationality: "Congolese" },
    { country: "Costa Rica", nationality: "Costa Rican" },
    { country: "Croatia", nationality: "Croatian" },
    { country: "Cuba", nationality: "Cuban" },
    { country: "Cyprus", nationality: "Cypriot" },
    { country: "Czechia (Czech Republic)", nationality: "Czech" },
    {
        country: "Democratic Republic of the Congo (Congo-Kinshasa)",
        nationality: "Congolese",
    },
    { country: "Denmark", nationality: "Danish" },
    { country: "Djibouti", nationality: "Djibouti" },
    { country: "Dominica", nationality: "Dominican" },
    { country: "Dominican Republic", nationality: "Dominican" },
    { country: "East Timor (Timor-Leste)", nationality: "East Timorese" },
    { country: "Ecuador", nationality: "Ecuadorian" },
    { country: "Egypt", nationality: "Egyptian" },
    { country: "El Salvador", nationality: "Salvadoran" },
    { country: "Equatorial Guinea", nationality: "Equatorial Guinean" },
    { country: "Eritrea", nationality: "Eritrean" },
    { country: "Estonia", nationality: "Estonian" },
    { country: "Eswatini (fmr. 'Swaziland')", nationality: "Swazi" },
    { country: "Ethiopia", nationality: "Ethiopian" },
    { country: "Fiji", nationality: "Fijian" },
    { country: "Finland", nationality: "Finnish" },
    { country: "France", nationality: "French" },
    { country: "Gabon", nationality: "Gabonese" },
    { country: "Gambia", nationality: "Gambian" },
    { country: "Georgia", nationality: "Georgian" },
    { country: "Germany", nationality: "German" },
    { country: "Ghana", nationality: "Ghanaian" },
    { country: "Greece", nationality: "Greek" },
    { country: "Grenada", nationality: "Grenadian" },
    { country: "Guatemala", nationality: "Guatemalan" },
    { country: "Guinea", nationality: "Guinean" },
    { country: "Guinea-Bissau", nationality: "Bissau-Guinean" },
    { country: "Guyana", nationality: "Guyanese" },
    { country: "Haiti", nationality: "Haitian" },
    { country: "Holy See", nationality: "Vatican" },
    { country: "Honduras", nationality: "Honduran" },
    { country: "Hungary", nationality: "Hungarian" },
    { country: "Iceland", nationality: "Icelander" },
    { country: "India", nationality: "Indian" },
    { country: "Indonesia", nationality: "Indonesian" },
    { country: "Iran", nationality: "Iranian" },
    { country: "Iraq", nationality: "Iraqi" },
    { country: "Ireland", nationality: "Irish" },
    { country: "Israel", nationality: "Israeli" },
    { country: "Italy", nationality: "Italian" },
    { country: "Ivory Coast", nationality: "Ivorian" },
    { country: "Jamaica", nationality: "Jamaican" },
    { country: "Japan", nationality: "Japanese" },
    { country: "Jordan", nationality: "Jordanian" },
    { country: "Kazakhstan", nationality: "Kazakhstani" },
    { country: "Kenya", nationality: "Kenyan" },
    { country: "Kiribati", nationality: "I-Kiribati" },
    { country: "Kuwait", nationality: "Kuwaiti" },
    { country: "Kyrgyzstan", nationality: "Kyrgyzstani" },
    { country: "Laos", nationality: "Laotian" },
    { country: "Latvia", nationality: "Latvian" },
    { country: "Lebanon", nationality: "Lebanese" },
    { country: "Lesotho", nationality: "Mosotho" },
    { country: "Liberia", nationality: "Liberian" },
    { country: "Libya", nationality: "Libyan" },
    { country: "Liechtenstein", nationality: "Liechtensteiner" },
    { country: "Lithuania", nationality: "Lithuanian" },
    { country: "Luxembourg", nationality: "Luxembourger" },
    { country: "Madagascar", nationality: "Malagasy" },
    { country: "Malawi", nationality: "Malawian" },
    { country: "Malaysia", nationality: "Malaysian" },
    { country: "Maldives", nationality: "Maldivian" },
    { country: "Mali", nationality: "Malian" },
    { country: "Malta", nationality: "Maltese" },
    { country: "Marshall Islands", nationality: "Marshallese" },
    { country: "Mauritania", nationality: "Mauritanian" },
    { country: "Mauritius", nationality: "Mauritian" },
    { country: "Mexico", nationality: "Mexican" },
    { country: "Micronesia", nationality: "Micronesian" },
    { country: "Moldova", nationality: "Moldovan" },
    { country: "Monaco", nationality: "Monacan" },
    { country: "Mongolia", nationality: "Mongolian" },
    { country: "Montenegro", nationality: "Montenegrin" },
    { country: "Morocco", nationality: "Moroccan" },
    { country: "Mozambique", nationality: "Mozambican" },
    { country: "Myanmar (Burma)", nationality: "Burmese" },
    { country: "Namibia", nationality: "Namibian" },
    { country: "Nauru", nationality: "Nauruan" },
    { country: "Nepal", nationality: "Nepali" },
    { country: "Netherlands", nationality: "Dutch" },
    { country: "New Zealand", nationality: "New Zealander" },
    { country: "Nicaragua", nationality: "Nicaraguan" },
    { country: "Niger", nationality: "Nigerien" },
    { country: "Nigeria", nationality: "Nigerian" },
    { country: "North Macedonia", nationality: "Macedonian" },
    { country: "Norway", nationality: "Norwegian" },
    { country: "Oman", nationality: "Omani" },
    { country: "Pakistan", nationality: "Pakistani" },
    { country: "Palau", nationality: "Palauan" },
    { country: "Palestine State", nationality: "Palestinian" },
    { country: "Panama", nationality: "Panamanian" },
    { country: "Papua New Guinea", nationality: "Papua New Guinean" },
    { country: "Paraguay", nationality: "Paraguayan" },
    { country: "Peru", nationality: "Peruvian" },
    { country: "Philippines", nationality: "Filipino" },
    { country: "Poland", nationality: "Polish" },
    { country: "Portugal", nationality: "Portuguese" },
    { country: "Qatar", nationality: "Qatari" },
    { country: "Romania", nationality: "Romanian" },
    { country: "Russia", nationality: "Russian" },
    { country: "Rwanda", nationality: "Rwandan" },
    { country: "Saint Kitts and Nevis", nationality: "Kittian and Nevisian" },
    { country: "Saint Lucia", nationality: "Saint Lucian" },
    {
        country: "Saint Vincent and the Grenadines",
        nationality: "Saint Vincentian",
    },
    { country: "Samoa", nationality: "Samoan" },
    { country: "San Marino", nationality: "Sammarinese" },
    { country: "Sao Tome and Principe", nationality: "Sao Tomean" },
    { country: "Saudi Arabia", nationality: "Saudi Arabian" },
    { country: "Senegal", nationality: "Senegalese" },
    { country: "Serbia", nationality: "Serbian" },
    { country: "Seychelles", nationality: "Seychellois" },
    { country: "Sierra Leone", nationality: "Sierra Leonean" },
    { country: "Singapore", nationality: "Singaporean" },
    { country: "Slovakia", nationality: "Slovak" },
    { country: "Slovenia", nationality: "Slovenian" },
    { country: "Solomon Islands", nationality: "Solomon Islander" },
    { country: "Somalia", nationality: "Somali" },
    { country: "South Africa", nationality: "South African" },
    { country: "South Korea", nationality: "South Korean" },
    { country: "South Sudan", nationality: "South Sudanese" },
    { country: "Spain", nationality: "Spanish" },
    { country: "Sri Lanka", nationality: "Sri Lankan" },
    { country: "Sudan", nationality: "Sudanese" },
    { country: "Suriname", nationality: "Surinamese" },
    { country: "Sweden", nationality: "Swedish" },
    { country: "Switzerland", nationality: "Swiss" },
    { country: "Syria", nationality: "Syrian" },
    { country: "Tajikistan", nationality: "Tajik" },
    { country: "Tanzania", nationality: "Tanzanian" },
    { country: "Thailand", nationality: "Thai" },
    { country: "Togo", nationality: "Togolese" },
    { country: "Tonga", nationality: "Tongan" },
    {
        country: "Trinidad and Tobago",
        nationality: "Trinidadian and Tobagonian",
    },
    { country: "Tunisia", nationality: "Tunisian" },
    { country: "Turkey", nationality: "Turkish" },
    { country: "Turkmenistan", nationality: "Turkmen" },
    { country: "Tuvalu", nationality: "Tuvaluan" },
    { country: "Uganda", nationality: "Ugandan" },
    { country: "Ukraine", nationality: "Ukrainian" },
    { country: "United Arab Emirates", nationality: "Emirati" },
    { country: "United Kingdom", nationality: "British" },
    { country: "United States", nationality: "American" },
    { country: "Uruguay", nationality: "Uruguayan" },
    { country: "Uzbekistan", nationality: "Uzbek" },
    { country: "Vanuatu", nationality: "Vanuatuan" },
    { country: "Venezuela", nationality: "Venezuelan" },
    { country: "Vietnam", nationality: "Vietnamese" },
    { country: "Yemen", nationality: "Yemeni" },
    { country: "Zambia", nationality: "Zambian" },
    { country: "Zimbabwe", nationality: "Zimbabwean" },
] as const;

export const findNationality = (
    countryName: (typeof countryArray)[number]["country"]
) => {
    const foundCountry = countryArray.find(
        (countryObj) => countryObj.country === countryName
    );
    if (foundCountry) {
        return foundCountry.nationality;
    } else {
        return null;
    }
};
